import { create } from "zustand";
import { persist } from "zustand/middleware";
import { workspaceStorage } from "./supabaseStorage";
import { fnv1a } from "../lib/domainChecklist";
import type { WorksheetAsk } from "../lib/manualWorksheet";

// The walkthrough questions (Describe / Show me) belonging to each check.
//
// These used to exist only inside a downloaded worksheet, regenerated by AI on
// every export. They are now a stored, viewable property of the check itself:
// generated once, shown on the check's row in the Audit Checklist Library,
// hand-editable there, and simply written out when the worksheet is exported.
// That is what makes the export an instant local file write with no AI calls.
//
// Keyed by CHECK ID, which is stable across text edits (a built-in keeps the id
// it was parsed with, and `edits` overrides only its text), so a question stays
// attached to its check when the check is reworded. Staleness is therefore not
// a key miss but an explicit comparison: `sourceHash` records the exact text the
// question was written from, and a check whose text no longer hashes to it is
// shown as stale rather than silently served as current.
//
// Persist key unchanged from when this was a hash-keyed export cache: renaming
// a store never changes its key, because existing workspaces are keyed by it.
// The shape did change, so version 1 migrates by dropping the old entries —
// they were keyed by content hash and carry no check id to re-attach them to.
// The only cost is regenerating, and nothing here feeds a prompt or a score.

const MAX_ENTRIES = 600;

export type StoredQuestion = {
  asks: WorksheetAsk[];
  // The check text these questions were written from. Staleness is a mismatch
  // against the check's current text, never a guess.
  sourceHash: string;
  generatedAt: string;
  // Hand-written by the user. Bulk regeneration skips these, so a reworded
  // question is never silently overwritten by a later "generate missing/stale".
  edited?: boolean;
};

export type WorksheetQuestionState = {
  entries: Record<string, StoredQuestion>;
  putMany: (next: Record<string, StoredQuestion>) => void;
  setEdited: (checkId: string, asks: WorksheetAsk[], sourceHash: string) => void;
  remove: (checkId: string) => void;
  clear: () => void;
};

const trim = (merged: Record<string, StoredQuestion>): Record<string, StoredQuestion> => {
  const keys = Object.keys(merged);
  if (keys.length <= MAX_ENTRIES) return merged;
  const keep = keys.slice(keys.length - MAX_ENTRIES);
  const out: Record<string, StoredQuestion> = {};
  for (const k of keep) out[k] = merged[k];
  return out;
};

export const useWorksheetQuestionStore = create<WorksheetQuestionState>()(
  persist(
    (set) => ({
      entries: {},

      // Generation result. A hand-edited question is preserved: regeneration
      // may only replace what the AI itself last wrote.
      putMany: (next) =>
        set((s) => {
          const merged = { ...s.entries };
          for (const [id, q] of Object.entries(next)) {
            if (merged[id]?.edited) continue;
            merged[id] = q;
          }
          return { entries: trim(merged) };
        }),

      // A hand edit. Marked `edited` so it survives every later regeneration,
      // and re-stamped with the current source hash so saving a question
      // against the check as it reads now clears the stale flag.
      setEdited: (checkId, asks, sourceHash) =>
        set((s) => ({
          entries: { ...s.entries, [checkId]: { asks, sourceHash, generatedAt: new Date().toISOString(), edited: true } },
        })),

      remove: (checkId) =>
        set((s) => {
          const entries = { ...s.entries };
          delete entries[checkId];
          return { entries };
        }),

      clear: () => set({ entries: {} }),
    }),
    {
      name: "ucc-gd4-worksheet-cache:v1",
      version: 1,
      storage: workspaceStorage,
      migrate: () => ({ entries: {} }),
    }
  )
);

export function currentWorksheetQuestions(): Record<string, StoredQuestion> {
  return useWorksheetQuestionStore.getState().entries;
}

// The check text a question was written from, hashed. One definition so the
// writer, the staleness badge and the tests cannot drift apart.
export function questionSourceHash(checkText: string): string {
  return fnv1a(checkText);
}

export type QuestionState = "missing" | "current" | "stale" | "edited" | "edited-stale";

// What to show against a check, and what "generate missing/stale" should pick
// up. An edited question that is also stale stays distinguishable, because
// bulk regeneration must skip it while the UI still warns it is behind.
export function questionStateFor(stored: StoredQuestion | undefined, checkText: string): QuestionState {
  if (!stored) return "missing";
  const fresh = stored.sourceHash === questionSourceHash(checkText);
  if (stored.edited) return fresh ? "edited" : "edited-stale";
  return fresh ? "current" : "stale";
}
