import { create } from "zustand";
import { persist } from "zustand/middleware";
import { workspaceStorage } from "./supabaseStorage";
import { fnv1a } from "../lib/domainChecklist";
import { newQuestionId, type AskType, type WorksheetQuestion } from "../lib/manualWorksheet";

// The walkthrough questions (Describe / Show me) belonging to each check.
//
// These used to exist only inside a downloaded worksheet, regenerated by AI on
// every export. They are now a stored, viewable property of the check itself:
// generated once, shown on the check's row in the Audit Checklist Library,
// hand-editable there, and simply written out when the worksheet is exported.
// That is what makes the export an instant local file write with no AI calls.
//
// Keyed by CHECK ID, which is stable across text edits (a built-in keeps the id
// it was parsed with, and `edits` overrides only its text), so a question stays
// attached to its check when the check is reworded. Staleness is therefore not
// a key miss but an explicit comparison: `sourceHash` records the exact text the
// question was written from, and a check whose text no longer hashes to it is
// shown as stale rather than silently served as current.
//
// Persist key unchanged from when this was a hash-keyed export cache: renaming
// a store never changes its key, because existing workspaces are keyed by it.
// The shape did change, so version 1 migrates by dropping the old entries —
// they were keyed by content hash and carry no check id to re-attach them to.
// The only cost is regenerating, and nothing here feeds a prompt or a score.

const MAX_ENTRIES = 600;

export type StoredQuestion = {
  questions: WorksheetQuestion[];
  // The check text these questions were written from. Staleness is a mismatch
  // against the check's current text, never a guess.
  sourceHash: string;
  generatedAt: string;
  // True once any question on this check was written or reworded by hand.
  // Kept for the "Your wording" badge; what actually protects a question from
  // regeneration is its own `source: "hand"`, per question.
  edited?: boolean;
};

export type WorksheetQuestionState = {
  entries: Record<string, StoredQuestion>;
  // Generation result: replaces the AI-written questions on each check and
  // leaves every hand-written one in place.
  putMany: (next: Record<string, { questions: WorksheetQuestion[]; sourceHash: string }>) => void;
  editQuestion: (checkId: string, questionId: string, text: string, askType: AskType) => void;
  addQuestion: (checkId: string, text: string, askType: AskType, sourceHash: string) => void;
  removeQuestion: (checkId: string, questionId: string) => void;
  moveQuestion: (checkId: string, questionId: string, delta: -1 | 1) => void;
  remove: (checkId: string) => void;
  clear: () => void;
};

const trim = (merged: Record<string, StoredQuestion>): Record<string, StoredQuestion> => {
  const keys = Object.keys(merged);
  if (keys.length <= MAX_ENTRIES) return merged;
  const keep = keys.slice(keys.length - MAX_ENTRIES);
  const out: Record<string, StoredQuestion> = {};
  for (const k of keep) out[k] = merged[k];
  return out;
};

const stamp = () => new Date().toISOString();

// Exported so the one-way v1 -> v2 conversion can be tested directly rather
// than only through a browser reload.
//
// v0 was a hash-keyed export cache with no check id to re-attach entries to.
// v1 stored a { describe, showMe } PAIR per ask; each half becomes its own
// question, which is lossless for the text.
//
// AI-written entries are deliberately given an EMPTY sourceHash so they read
// as stale and the bulk action rewrites them under the new single-question
// prompt. That duplication is exactly what this change exists to remove, and
// deriving a merged question from the two halves cannot remove it, because the
// redundancy is in the content rather than the layout. Hand-written entries
// keep their hash, so they stay "Your wording" and are never touched.
export function migrateWorksheetQuestions(persisted: unknown, from: number): { entries: Record<string, StoredQuestion> } {
  if (from < 1) return { entries: {} };
  const old = persisted as { entries?: Record<string, { asks?: { describe?: string; showMe?: string }[]; sourceHash?: string; generatedAt?: string; edited?: boolean }> };
  const entries: Record<string, StoredQuestion> = {};
  for (const [id, e] of Object.entries(old?.entries ?? {})) {
    const hand = e.edited === true;
    const questions: WorksheetQuestion[] = [];
    for (const a of e.asks ?? []) {
      if (a.describe?.trim()) questions.push({ id: newQuestionId(), text: a.describe.trim(), askType: "Process", source: hand ? "hand" : "ai" });
      if (a.showMe?.trim()) questions.push({ id: newQuestionId(), text: a.showMe.trim(), askType: "Document", source: hand ? "hand" : "ai" });
    }
    if (questions.length === 0) continue;
    entries[id] = { questions, sourceHash: hand ? (e.sourceHash ?? "") : "", generatedAt: e.generatedAt ?? stamp(), edited: hand };
  }
  return { entries };
}



// Applies a change to one check's question list, creating the entry if the
// check had none (which is how a hand-added question works on a check nobody
// has generated for yet).
const edit = (
  s: WorksheetQuestionState,
  checkId: string,
  fn: (qs: WorksheetQuestion[]) => WorksheetQuestion[],
  sourceHash?: string,
): { entries: Record<string, StoredQuestion> } => {
  const prev = s.entries[checkId];
  const questions = fn(prev?.questions ?? []);
  return {
    entries: {
      ...s.entries,
      [checkId]: {
        questions,
        sourceHash: sourceHash ?? prev?.sourceHash ?? "",
        generatedAt: prev?.generatedAt ?? stamp(),
        edited: true,
      },
    },
  };
};

export const useWorksheetQuestionStore = create<WorksheetQuestionState>()(
  persist(
    (set) => ({
      entries: {},

      // Regeneration replaces only what the AI itself last wrote. Every
      // question Felix wrote or reworded is kept, and kept in front, so a
      // bulk regeneration can never silently undo his work.
      putMany: (next) =>
        set((s) => {
          const merged = { ...s.entries };
          for (const [id, { questions, sourceHash }] of Object.entries(next)) {
            const kept = (merged[id]?.questions ?? []).filter((q) => q.source === "hand");
            merged[id] = {
              questions: [...kept, ...questions],
              sourceHash,
              generatedAt: stamp(),
              edited: kept.length > 0,
            };
          }
          return { entries: trim(merged) };
        }),

      // Reworded by hand: it becomes a hand question, so later regenerations
      // leave it alone.
      editQuestion: (checkId, questionId, text, askType) =>
        set((s) => edit(s, checkId, (qs) => qs.map((q) => (q.id === questionId ? { ...q, text, askType, source: "hand" } : q)))),

      addQuestion: (checkId, text, askType, sourceHash) =>
        set((s) => edit(s, checkId, (qs) => [...qs, { id: newQuestionId(), text, askType, source: "hand" }], s.entries[checkId]?.sourceHash ?? sourceHash)),

      removeQuestion: (checkId, questionId) =>
        set((s) => edit(s, checkId, (qs) => qs.filter((q) => q.id !== questionId))),

      moveQuestion: (checkId, questionId, delta) =>
        set((s) => edit(s, checkId, (qs) => {
          const i = qs.findIndex((q) => q.id === questionId);
          const j = i + delta;
          if (i < 0 || j < 0 || j >= qs.length) return qs;
          const out = [...qs];
          [out[i], out[j]] = [out[j], out[i]];
          return out;
        })),

      remove: (checkId) =>
        set((s) => {
          const entries = { ...s.entries };
          delete entries[checkId];
          return { entries };
        }),

      clear: () => set({ entries: {} }),
    }),
    {
      name: "ucc-gd4-worksheet-cache:v1",
      version: 2,
      storage: workspaceStorage,
      migrate: (persisted, from) => migrateWorksheetQuestions(persisted, from),
    }
  )
);

export function currentWorksheetQuestions(): Record<string, StoredQuestion> {
  return useWorksheetQuestionStore.getState().entries;
}

// The check text a question was written from, hashed. One definition so the
// writer, the staleness badge and the tests cannot drift apart.
export function questionSourceHash(checkText: string): string {
  return fnv1a(checkText);
}

export type QuestionState = "missing" | "current" | "stale" | "edited" | "edited-stale";

// What to show against a check, and what "generate missing/stale" should pick
// up. An edited question that is also stale stays distinguishable, because
// bulk regeneration must skip it while the UI still warns it is behind.
export function questionStateFor(stored: StoredQuestion | undefined, checkText: string): QuestionState {
  if (!stored) return "missing";
  const fresh = stored.sourceHash === questionSourceHash(checkText);
  if (stored.edited) return fresh ? "edited" : "edited-stale";
  return fresh ? "current" : "stale";
}
